[versions]
spotless = "6.25.0"
kotlin = "2.0.21"
ktlint = "1.1.1"

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
